trigger:
- master
- releases/*

jobs:
  - job: Test_Linux
    displayName: Run Tests on Linux
    pool:
      vmImage: "Ubuntu 16.04"
    variables:
      run_coveralls: true
    strategy:
      matrix:
        Node_v10:
          node_version: 10
        Node_v8:
          node_version: 8
        Node_v6:
          node_version: 6
        Node_v4:
          node_version: 4
        Node_v0_12:
          node_version: 0.12
        Node_v0_10:
          node_version: 0.10
    steps:
      - template: .azure-pipelines-steps.yml

  - job: Test_Windows
    displayName: Run Tests on Windows
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        Node_v10:
          node_version: 10
        Node_v8:
          node_version: 8
        Node_v6:
          node_version: 6
        Node_v4:
          node_version: 4
          npm_version: 2
        Node_v0_12:
          node_version: 0.12
          npm_version: 2
        Node_v0_10:
          node_version: 0.10
          npm_version: 2
    steps:
      - template: .azure-pipelines-steps.yml

  - job: Test_MacOS
    displayName: Run Tests on MacOS
    pool:
      vmImage: macos-10.13
    strategy:
      matrix:
        Node_v10:
          node_version: 10
        Node_v8:
          node_version: 8
        Node_v6:
          node_version: 6
        Node_v4:
          node_version: 4
        Node_v0_12:
          node_version: 0.12
        Node_v0_10:
          node_version: 0.10
    steps:
      - template: .azure-pipelines-steps.yml

  - job: Notify_Coveralls
    displayName: Notify Coveralls that the parallel report is done
    dependsOn:
      - Test_Linux
      - Test_Windows
      - Test_MacOS
    env:
      COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN_SECRET)
      COVERALLS_SERVICE_JOB_ID: $(Build.BuildNumber)
    steps:
      - script: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$COVERALLS_SERVICE_JOB_ID&payload[status]=done"
